nodeLinker: pnp

npmScopes:
  hoeeeeeh:
    npmRegistryServer: "https://npm.pkg.github.com/"

plugins:
  - ./.yarn/plugin-env-npm.js

yarnPath: .yarn/releases/yarn-4.5.1.cjs


packageExtensions:
  '@typescript-eslint/utils@*':
    peerDependencies:
      eslint: '*'
      typescript: '*'
  '@typescript-eslint/type-utils@*':
    peerDependencies:
      eslint: '*'
      typescript: '*'
  'typescript-eslint@*':
    peerDependencies:
      eslint: '*'
