nodeLinker: pnp

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.5.1.cjs

packageExtensions:
  '@typescript-eslint/utils@*':
    peerDependencies:
      eslint: '*'
      typescript: '*'
  '@typescript-eslint/type-utils@*':
    peerDependencies:
      eslint: '*'
      typescript: '*'
  'typescript-eslint@*':
    peerDependencies:
      eslint: '*'
