# docker-compose.yml
version: '3.8'

services:
  frontend:
    image: liboost/frontend-index-server
    build:
      context: .
      dockerfile: ./frontend/dockerfile
    depends_on:
      # - backend
      - nginx

#  backend:
#    build:
#      context: ./backend
#    volumes:
#      - ./docker-compose.backend.yml:/app/docker-compose.backend.yml  # backend의 하위 구성 포함
#      - .:/app  # 소스 코드 전체 마운트
#      - yarn-lock:/app/yarn.lock  # yarn.lock 파일을 공통 볼륨으로 마운트
#    command: docker-compose -f /app/docker-compose.backend.yml up
#    depends_on:
#      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx  # Nginx 설정 파일을 컨테이너에 마운트



