# docker-compose.yml
version: '3.8'

services:
  nginx:
    build:
      context: nginx
      dockerfile: dockerfile
    image: liboost/nginx:latest
    ports:
      - "80:80"
    networks:
      - default-network

  backend-rtmp-server:
    container_name: rtmp-container
    build:
      context: backend/rtmpServer
      dockerfile: dockerfile
    image: liboost/backend-rtmp-server:latest
    env_file: backend/.env
    ports:
      - 8000:8000
      - 1935:1935
    networks:
      - default-network
      - backend-bridge


networks:
  backend-bridge:
    driver: bridge
    name: media-server

  default-network:
    driver: bridge
