# docker-compose.yml
version: '3.8'

services:
  frontend-builder:
#    image: liboost/frontend-index-server
    build:
      context: .
      dockerfile: ./frontend/dockerfile
    volumes:
      - ./frontend-dist:/app/.dist  # 빌드 결과를 공유하기 위한 볼륨 설정
    networks:
      - default-network
    command: ["yarn", "build"]

  nginx:
    build:
      context: nginx
      dockerfile: dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend-dist:/usr/share/nginx/html  # 빌드된 결과를 Nginx에서 서빙
    networks:
      - default-network
    depends_on:
      - frontend-builder
#  backend:
#    build:
#      context: ./backend
#    volumes:
#      - ./docker-compose.backend.yml:/app/docker-compose.backend.yml  # backend의 하위 구성 포함
#      - .:/app  # 소스 코드 전체 마운트
#      - yarn-lock:/app/yarn.lock  # yarn.lock 파일을 공통 볼륨으로 마운트
#    command: docker-compose -f /app/docker-compose.backend.yml up
#    depends_on:
#      - nginx
#  networks:
#    - default-network


networks:
  default-network:
    driver: bridge

volumes:
  frontend-dist:   # 프론트엔드 빌드 결과를 저장하는 볼륨
